### ISSUE TITLE
[FR] Target WASM?

### ISSUE THREAD

**Issue by glyh** [FastVM/minivm#15]
As title, it would be good if this VM can work under WASM, so that dynamic languages' compiler can be easily implemented. 

Thank you.

**Comment by glyh** [comment]
Nevermind, I found no point doing this.

**Comment by Bubuche87** [comment]
I don't know if it's appropriate to post that here or if I should create a new topic.
I came to post a request for exactly that : a wasm version of this VM.
I am especially interested in the fact that it's possible to snapshot/dump the state of the machine and restore it later , plus specifying how many instructions it can run before being interrupted.

Those features+wasm support would make it an ideal component for "fantasy console" programs.
Many people use Lua for that, because it's there and is fast, but it's not an appropriate tool for this. Because it's hard/impossible to snapshot memory and guarantee a framerate, because the language is too powerful for retro games.
( I also think wasm is bloated and inappropriate for this scenario).

So I upvote the request for a wasm version of it.
